name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.28
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_USER: db_user_test
          MYSQL_PASSWORD: db_password_test
          MYSQL_DATABASE: db_name_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql

      - name: Install Dependencies
        run: composer install

      - name: Set up Test Environment
        run: |
          echo "DATABASE_URL_TEST=mysql://db_user_test:db_password_test@localhost:3306/db_name_test" > .env.test

      - name: Set up Test Database
        run: |
          # Check if there are migrations available
          if [ -z "$(php bin/console doctrine:migrations:status --env=test)" ]; then
            # No migrations available, use doctrine:schema:create
            php bin/console doctrine:schema:create --env=test
          else
            # Migrations available, run migrations with --no-interaction parameter
            php bin/console doctrine:migrations:migrate --env=test --no-interaction
          fi

          # Load fixtures (change the command to your specific fixtures loading method)
          php bin/console doctrine:fixtures:load --env=test --no-interaction --group=TestFixtures

      - name: Run PHPUnit Tests with Test Database
        run: php bin/phpunit
