name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.28
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql

      - name: Install Dependencies
        run: composer install

      - name: Set up Test Environment
        run: |
          # Create .env.test file from the template if it doesn't exist
          if [ ! -f .env.test ]; then
            cp .env.test.template .env.test
          fi

          # Replace placeholders in .env.test with actual database credentials if not already set
          sed -i 's/DB_HOST=/DB_HOST=127.0.0.1/g' .env.test
          sed -i 's/DB_USERNAME=/DB_USERNAME=root/g' .env.test
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=root_password/g' .env.test
          sed -i 's/DB_DATABASE=/DB_DATABASE=test_database/g' .env.test

      - name: Set up Test Database
        run: |
          # Run migrations
          php bin/console doctrine:migrations:migrate --env=test --no-interaction

          # Load fixtures (change the command to your specific fixtures loading method)
          php bin/console doctrine:fixtures:load --env=test --no-interaction --group=TestFixtures

      - name: Run PHPUnit Tests with Test Database
        run: php bin/phpunit
